### ISSUE TITLE
Docker-compose deployment

### ISSUE THREAD

**Issue by meichthys** [ptpb/pb#253]
I tried a docker-compose deployment using an image from dockerhub without success. Could someone take a look at my docker-compose below and let me know if something looks off?

```
version: "3"
services:
  pb:
    container_name: pb
    image: ptpb/pb
    ports:
      - '10008:10002'
    volumes:
      - pb_data:/pb
    environment:
      - 'LISTEN_ADDRESS=::'
      - 'LISTEN_PORT=10008'
      - 'CDN_PREFIX=//d34zelngniy2d8.cloudfront.net'

  pb_mongodb:
    container_name: mongodb_pb
    image: mongo:latest

volumes:
  pb_data:
```
After running `docker-compose up -d` I cannot access: `http://docker_ip_address:10008` 😕
